### ISSUE TITLE
server error: window is not defined

### ISSUE THREAD

**Issue by Lazy-xiaoqi** [hemengke1997/vite-plugin-remix-flat-route#1]
https://github.com/hemengke1997/vite-plugin-i18n-ally/tree/master/playground/remix-ssr

**Comment by Lazy-xiaoqi** [comment]
Pull the latest code and run it to report an error

**Comment by hemengke1997** [comment]
fixed, please pull code again.

**Comment by Lazy-xiaoqi** [comment]
ok thanks
